{
    'name': "Thoo8 SMS Gateway",
    "description": """Thoo8 SMS Gateway allows easy SMS sending, managing multiple providers, dynamic templates, message logging, and success verification.""",
    'summary': "Gateway for sending SMS messages through multiple providers",
    'version': '15.0.1.1.0',
    'category': 'Tools',
    'author': "Saleh Ibrhaim - thoo8",
    'company': 'thoo8',
    'maintainer': 'thoo8',
    'website': "http://www.thoo8.com",
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/sms_provider_data.xml',
        'data/sms_test_template_data.xml',
        'wizard/test_sms_wizard.xml',
        'wizard/template_field.xml',
        'views/sms_provider_views.xml',
        'views/sms_template_views.xml',
        'views/sms_log_views.xml',
        'views/sms_menu_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'images': [
        'static/description/banner.png',
        'static/description/icon.png',
        'static/description/sms_gateway_001.jpg',
        'static/description/sms_gateway_002.jpg',
        'static/description/sms_gateway_003.jpg',
        'static/description/sms_gateway_004.jpg',
        'static/description/sms_gateway_005.jpg',
        'static/description/sms_gateway_006.jpg',
        'static/description/sms_gateway_007.jpg',
        'static/description/sms_gateway_008.jpg',
        'static/description/sms_gateway_009.jpg',
        'static/description/sms_gateway_010.jpg',
        'static/description/sms_gateway_011.jpg',
        'static/description/sms_gateway_012.jpg',
        'static/description/sms_gateway_013.jpg',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
